# -*- mode:python -*-

# Authors: Jiayi Huang

Import('*')

if env['PROTOCOL'] == 'None':
    Return()

SimObject('BooksimNetwork.py')

Source('batchtrafficmanager.cc')
Source('booksim_config.cc')
Source('booksim_main.cc')
Source('BooksimNetwork.cc')
Source('buffer.cc')
Source('buffer_state.cc')
Source('config_utils.cc')
Source('credit.cc')
Source('flit.cc')
Source('flitchannel.cc')
Source('flovtrafficmanager.cc')
Source('handshake.cc')
Source('gem5trafficmanager.cc')
Source('injection.cc')
Source('lex.yy.c')
Source('misc_utils.cc')
Source('module.cc')
Source('outputset.cc')
Source('packet_reply_info.cc')
Source('random_utils.cc')
#Source('rng.c')
#Source('rng-double.c')
Source('rng_wrapper.cc')
Source('rng_double_wrapper.cc')
Source('routefunc.cc')
Source('routetbl.cc')
Source('rptrafficmanager.cc')
Source('stats.cc')
Source('traffic.cc')
Source('trafficmanager.cc')
Source('vc.cc')
Source('y.tab.c')
